-- =============================================================================
-- lua/plugins/pyright-override.lua
--
-- Configures pyright LSP to use the pyrightconfig.json generated by the
-- entrypoint script when a venv is detected in the project root.
--
-- The entrypoint sets DVIM_PYRIGHT_CONFIG env var to the config file path:
--   - /tmp/pyrightconfig.json   if a .venv or venv was auto-detected
--   - project pyrightconfig.json path if user has one
--   - empty string              if no venv and no user config found
--
-- When empty, pyright starts normally and will use pyproject.toml if present
-- or fall back to global python.
-- =============================================================================
return {
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      pyright = {
        -- Read the config path set by entrypoint.sh
        -- This runs when the LSP starts, so it picks up the env var correctly
        on_new_config = function(config, root_dir)
          local pyright_config = os.getenv("DVIM_PYRIGHT_CONFIG")

          if pyright_config and pyright_config ~= "" then
            -- Point pyright at our generated config
            config.cmd_env = config.cmd_env or {}
            config.cmd_env.PYRIGHT_CONFIG_FILE = pyright_config

            -- Also pass as a root-level override via initializationOptions
            config.settings = config.settings or {}
            config.settings.python = config.settings.python or {}

            -- Read venv info from the generated config and pass to pyright
            local ok, cfg_content = pcall(function()
              local f = io.open(pyright_config, "r")
              if not f then return nil end
              local content = f:read("*a")
              f:close()
              return content
            end)

            if ok and cfg_content then
              -- Extract venvPath and venv from the JSON we generated
              local venv_path = cfg_content:match('"venvPath"%s*:%s*"([^"]+)"')
              local venv      = cfg_content:match('"venv"%s*:%s*"([^"]+)"')

              if venv_path and venv then
                config.settings.python.venvPath = venv_path
                config.settings.python.venv = venv
                vim.notify(
                  string.format("[dvim] pyright: using venv '%s' in %s", venv, venv_path),
                  vim.log.levels.INFO
                )
              end
            end
          else
            -- No venv detected — let pyright discover config naturally
            -- It will find pyproject.toml or pyrightconfig.json if present
            vim.notify("[dvim] pyright: no venv detected, using project/global config", vim.log.levels.DEBUG)
          end
        end,
      },
    },
  },
}