-- =============================================================================
-- lua/config/user.lua
--
-- Baked stub — automatically loaded by LazyVim via options.lua.
-- Sources user and project configs if they are mounted by the dvim launcher.
--
-- DO NOT EDIT THIS FILE inside the container — it will be lost on rebuild.
-- Instead:
--   System-wide config:  ~/.config/dvim/user.lua   on your host
--   Project config:      .dvim.lua                 in your project root
-- =============================================================================

-- System-wide user config (~/.config/dvim/user.lua on host)
-- Mounted by dvim launcher to: lua/dvim/user.lua
local ok_user, err_user = pcall(require, "dvim.user")
if not ok_user and not err_user:match("module.*not found") then
  vim.notify("[dvim] Error in user config: " .. err_user, vim.log.levels.ERROR)
end

-- Project-level config (.dvim.lua in project root on host)
-- Mounted by dvim launcher to: lua/dvim/project.lua
local ok_proj, err_proj = pcall(require, "dvim.project")
if not ok_proj and not err_proj:match("module.*not found") then
  vim.notify("[dvim] Error in project config: " .. err_proj, vim.log.levels.ERROR)
end